### ISSUE TITLE
moving to https://github.com/makingsensetraining

### ISSUE THREAD

**Issue by mravinale** [makingsensetraining/board-poc#4]
I was think to move this repository to https://github.com/makingsensetraining since in this main repository we can put more mature projects

what do you think @andresmoschini @lmarquezMS  @lucasasecas

**Comment by andresmoschini** [comment]
It is a possibility, let talk about it when I back from my holidays.

**Comment by andresmoschini** [comment]
Hi @mravinale, I think that it is a good idea. Should we change the ownership of this repo from [Making Sense](https://github.com/MakingSense) to [MakingSense Training](https://github.com/makingsensetraining), right?

After that, to reconfigure clients upstream remote is recommended, but not require because GitHub generate the redirections.

**Comment by mravinale** [comment]
@andresmoschini ok, I'll do that

**Comment by andresmoschini** [comment]
Great. Since I have created the repository, I am not sure if you can transfer ownership. If you cannot, let me know and I can.

**Comment by mravinale** [comment]
Oohh I can't please @andresmoschini could you do it? you have owner permissions in MakingSense Training

**Comment by andresmoschini** [comment]
Sure, doing that...

**Comment by andresmoschini** [comment]
Done!
